name: liquiddart
description: A Dart port of the Liquid template engine — supports Flutter, Dart CLI, and web.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.9.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
